# Generated by Django 5.0.1 on 2026-04-06 06:24

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], help_text='Income or Expense', max_length=10)),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('BUSINESS', 'Business'), ('INVESTMENT', 'Investment'), ('GIFT', 'Gift'), ('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('UTILITIES', 'Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('SHOPPING', 'Shopping'), ('EDUCATION', 'Education'), ('RENT', 'Rent'), ('OTHER', 'Other')], help_text='Transaction category', max_length=20)),
                ('date', models.DateField(help_text='Date when transaction occurred')),
                ('description', models.TextField(blank=True, help_text='Additional notes about this transaction')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete - record is hidden but not removed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'db_table': 'financial_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
