# Generated by Django 5.0.1 on 2026-04-06 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='user',
            field=models.ForeignKey(help_text='User who owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['user', 'date'], name='financial_r_user_id_497cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['type', 'category'], name='financial_r_type_7751ba_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['date'], name='financial_r_date_c7ef46_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['is_deleted'], name='financial_r_is_dele_213f2d_idx'),
        ),
    ]
